######
# Generic install for nightly
######

- hosts: all
  roles:
    - role: influxdb
      influxdb_install_url: https://s3-us-west-1.amazonaws.com/influxdb-nightly/influxdb_nightly_amd64.deb
      when: ansible_os_family == "Debian"
    - role: influxdb      
      influxdb_install_url: https://s3-us-west-1.amazonaws.com/influxdb-nightly/influxdb-nightly.x86_64.rpm
      when: ansible_os_family == "RedHat"


