---
#
# Caveats:
# - Boto must be installed for the system (not just the local session)
#
# - AWS credentials must be added to ~/.boto file under a [Credentials] heading.
#
# - SSH must be configured already. Here is my configuration (~/.ssh/config): 
#     Host 54.*
#       User ubuntu
#       IdentityFile ~/.ssh/cluster_testing_ssh
#       StrictHostKeyChecking no
#   If you don't want to configure SSH, you can specify the private key with
#   the `ansible-playbook` command by using the `--private-key=<path>` param
#
# - The `ansible-playbook` command requires an inventory file to be specified
#   at runtime. Since no inventory is used by this playbook, at the very
#   least you will need to have a dummy inventory file with 'localhost' as
#   the only line.
#
# - You may also want to specify the 'ubuntu' user as the user to use when
#   executing commands.
#
# - Only three servers per cluster is supported right now. Modifications to
#   the influxdb role are required to support more.
# 
- hosts:
    - localhost
  connection: local
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Create InfluxDB instances
      local_action:
        module: ec2
        key_name: "{{ instance_ssh_key }}"
        group: "{{ instance_security_group }}"
        instance_type: "{{ influxdb_instance_size }}"
        region: us-west-1
        image: "{{ influxdb_instance_ami }}"
        wait: yes
        wait_timeout: 500
        count: "{{ influxdb_instance_count }}"
        instance_tags:
          Name: cluster-testing-influxdb-{{ ansible_date_time.epoch }}
          test-type: clustering
          instance-type: influxdb
        vpc_subnet_id: "{{ instance_subnet_id }}"
        assign_public_ip: yes
      register: influxdb_provision_output

    - name: Create stress instances
      local_action:
        module: ec2
        key_name: "{{ instance_ssh_key }}"
        group: "{{ instance_security_group }}"
        instance_type: "{{ influxdb_instance_size }}"
        region: us-west-1
        image: "{{ stress_instance_ami }}"
        wait: yes
        wait_timeout: 500
        count: "{{ stress_instance_count }}"
        instance_tags:
          Name: cluster-testing-stress-{{ ansible_date_time.epoch }}
          test-type: clustering
          instance-type: stress
        vpc_subnet_id: "{{ instance_subnet_id }}"
        assign_public_ip: yes
      register: stress_provision_output
    
    - name: A moment of silence
      pause: minutes=2
      
    - name: Add InfluxDB hosts to inventory
      add_host: hostname={{ item.public_ip }} groups=influxdb
      with_items: "{{ influxdb_provision_output.instances }}"

    - name: Add stress hosts to inventory
      add_host: hostname={{ item.public_ip }} groups=stress
      with_items: "{{ stress_provision_output.instances }}"

# Apparently this needs to be run to re-gather facts for the new instances
- hosts:
    - influxdb
    - stress
  user: ubuntu
  become: yes
  gather_facts: yes
  tasks:
    []
      
- hosts: influxdb
  user: ubuntu
  become: yes
  vars_files:
    - ../../influxdb/defaults/main.yml
    - ../../influxdb/vars/main.yml
    - ../../telegraf/defaults/main.yml
    - ../../telegraf/vars/main.yml
    - defaults/main.yml
  tasks:
    - include: ../../influxdb/tasks/main.yml
      influxdb_cluster_servers: yes
    - include: ../../telegraf/tasks/main.yml
      telegraf_runas_user: root
      telegraf_runas_group: root
      telegraf_plugins_enabled:
        - cpu
        - disk
        - io
        - mem
        - swap
        - system
        - procstat.specifications
      telegraf_plugin_settings:
        cpu:
          percpu: "true"
          totalcpu: "true"
          drop:
            - cpu_time
        disk:
        io:
          skip_serial_number: "true"
        procstat.specifications:
          exe: influxd
          prefix: influxdb
      telegraf_tags:
        id: "{{ test_id }}"
        name: "{{ test_name }}"          
      telegraf_influxdb_urls:
        - http{% if telegraf_use_https %}s{% endif %}://{{ stress_results_server_hostname }}:8086
  handlers:
    - include: ../../influxdb/handlers/main.yml
    - include: ../../telegraf/handlers/main.yml

- hosts: stress
  user: ubuntu
  become: yes
  vars_files:
    - ../../influxdb/defaults/main.yml
    - ../../influxdb/vars/main.yml
    - defaults/main.yml
  tasks:
    - include: ../../influxdb/tasks/main.yml
      vars:
        influxdb_start_service: no
        influxdb_cluster_servers: no
  handlers:
    - include: ../../influxdb/handlers/main.yml
